import { Kategorie } from "./kategorie";
import { media } from "./media";
import { producent } from "./producent";
import { promocje } from "./promocje";
import { Products } from "./types";
import { w } from "./warianty";

export const products: Products[] = [
    {
        slug: "",
        nazwa: "Bielenda szampon do włosów zniszczonych",
        cena_skupu: 38.12,
        cena: 49.99,
        dostepnosc: "Duża",
        kategoria: [Kategorie[0]],
        producent: producent[1],
        media: [media[0]],
        promocje: null,
        opis: "No se jest taki szampoon, nie wiem co więcej na ten temat napisać, ale potrzebuje coś żeby było widać i czaił temat potem na stornei mimo tego żę robię to offstrona bo przecież nie mogę wstawić sobie normalnie wpisać to do\nstrony bo komuś się nie chciało kurwa jeszcze zrobić tego jebanego admin panelu",
        ilosc: 100,
        czas_wysylki: 5,
        kod_produkcyjny: "BND-9122231",
        ocena: 0,
        opinie: null,
        wariant: [w[3], w[4], w[5], w[6], w[8]],
        vat: 23,
        kod_ean: null,
        sku: null,
        aktywne: true,
    },
    {
        slug: "",
        nazwa: "Bielenda szampon odżywiający",
        cena_skupu: 42.12,
        cena: 59.99,
        dostepnosc: "Duża",
        kategoria: [Kategorie[0]],
        producent: producent[1],
        media: [media[0]],
        promocje: null,
        opis: "No se jest taki szampoon, nie wiem co więcej na ten temat napisać, ale potrzebuje coś żeby było widać i czaił temat potem na stornei mimo tego żę robię to offstrona bo przecież nie mogę wstawić sobie normalnie wpisać to do\nstrony bo komuś się nie chciało kurwa jeszcze zrobić tego jebanego admin panelu",
        ilosc: 100,
        czas_wysylki: 5,
        kod_produkcyjny: "BND-9122331",
        ocena: 0,
        opinie: null,
        wariant: [w[3], w[4], w[5], w[7]],
        vat: 23,
        kod_ean: null,
        sku: null,
        aktywne: true,
    },
    {
        slug: "",
        nazwa: "Krzesło damskie do strzyżenia",
        cena_skupu: 1239.12,
        cena: 1849.99,
        dostepnosc: "Duża",
        kategoria: [Kategorie[1]],
        producent: producent[0],
        media: [media[0]],
        promocje: promocje[0],
        opis: "No se jest taki krzeseł",
        ilosc: 100,
        czas_wysylki: 5,
        kod_produkcyjny: "WSN-9331231",
        ocena: 0,
        opinie: null,
        wariant: [w[0], w[1], w[2]],
        vat: 23,
        kod_ean: null,
        sku: null,
        aktywne: true,
    },
    {
        slug: "",
        nazwa: "Krzesło męskie do strzyżenia",
        cena_skupu: 1239.12,
        cena: 1819.99,
        dostepnosc: "Duża",
        kategoria: [Kategorie[1]],
        producent: producent[0],
        media: [media[0]],
        promocje: null,
        opis: "No se jest taki krzeseł",
        ilosc: 100,
        czas_wysylki: 5,
        kod_produkcyjny: "WSN-9031231",
        ocena: 0,
        opinie: null,
        wariant: [w[0], w[1], w[2]],
        vat: 23,
        kod_ean: null,
        sku: null,
        aktywne: true,
    },
    {
        slug: "",
        nazwa: "Narzuta do strzyżenia",
        cena_skupu: 39.12,
        cena: 78.99,
        dostepnosc: "Duża",
        kategoria: [Kategorie[2]],
        producent: producent[0],
        media: [media[0]],
        promocje: promocje[1],
        opis: "No se narzuta do strzyżenia żeby te jebane włochy nie były na kliencie",
        ilosc: 100,
        czas_wysylki: 5,
        kod_produkcyjny: "CCH-1331231",
        ocena: 0,
        opinie: null,
        wariant: [w[9], w[10], w[11]],
        vat: 23,
        kod_ean: null,
        sku: null,
        aktywne: true,
    },
];
