import { Warianty } from "./types";

export const w: Warianty[] = [
    // [0] czarny
    {
        nazwa: "Czarny",
        slug: "czarny",
        typ: "kolor",
        kolory: null,
        rozmiary: null,
        objetosc: null,
        nadpisuje_cene: false,
        inna_cena_skupu: false,
    },
    // [1] czerwony + nowa_cena
    {
        nazwa: "Czerwony",
        slug: "czerwony",
        typ: "kolor",
        kolory: null,
        rozmiary: null,
        objetosc: null,
        nadpisuje_cene: true,
        nowa_cena: 2149.99,
        inna_cena_skupu: false,
    },
    // [2] zolty + nowa_cena + cena_skupu
    {
        nazwa: "Żółty",
        slug: "zolty",
        typ: "kolor",
        kolory: null,
        rozmiary: null,
        objetosc: null,
        nadpisuje_cene: true,
        nowa_cena: 2151.99,
        inna_cena_skupu: true,
        cena_skupu: 1678.32,
    },
    // [3] 180ml
    {
        nazwa: "180ml",
        slug: "180ml",
        typ: "objetosc",
        kolory: null,
        rozmiary: null,
        objetosc: 180,
        nadpisuje_cene: false,
        inna_cena_skupu: false,
    },
    // [4] 180ml + specjalna + nowa_cena
    {
        nazwa: "180ml",
        slug: "180ml",
        typ: "objetosc",
        kolory: null,
        rozmiary: null,
        objetosc: 180,
        nadpisuje_cene: true,
        permisje: 1,
        nowa_cena: 34.99,
        inna_cena_skupu: false,
    },
    // [5] 280ml + nowa_cena + cena_skupu
    {
        nazwa: "280ml",
        slug: "280ml",
        typ: "objetosc",
        kolory: null,
        rozmiary: null,
        objetosc: 280,
        nadpisuje_cene: true,
        nowa_cena: 69.99,
        inna_cena_skupu: true,
        cena_skupu: 38.32,
    },
    // [6] 280ml + nowa_cena + specjalna + cena_skupu
    {
        nazwa: "280ml",
        slug: "280ml",
        typ: "objetosc",
        kolory: null,
        rozmiary: null,
        objetosc: 280,
        nadpisuje_cene: true,
        permisje: 3,
        nowa_cena: 32.17,
        inna_cena_skupu: true,
        cena_skupu: 28.32,
    },
    // [7] 520ml + specjalna + nowa_cena + cena_skupu
    {
        nazwa: "520ml",
        slug: "520ml",
        typ: "objetosc",
        kolory: null,
        rozmiary: null,
        objetosc: 520,
        nadpisuje_cene: true,
        permisje: 5,
        nowa_cena: 49.74,
        inna_cena_skupu: true,
        cena_skupu: 40.21,
    },
    // [8] 520ml + nowa_cena + cena_skupu
    {
        nazwa: "520ml",
        slug: "520ml",
        typ: "objetosc",
        kolory: null,
        rozmiary: null,
        objetosc: 520,
        nadpisuje_cene: true,
        nowa_cena: 99.99,
        inna_cena_skupu: true,
        cena_skupu: 40.21,
    },
    // [9] L - baza
    {
        nazwa: "L",
        slug: "large",
        typ: "rozmiar",
        kolory: null,
        rozmiary: null,
        objetosc: null,
        nadpisuje_cene: false,
        inna_cena_skupu: false,
    },
    // [10] L - specjalna
    {
        nazwa: "L",
        slug: "large",
        typ: "rozmiar",
        kolory: null,
        rozmiary: null,
        objetosc: null,
        nadpisuje_cene: true,
        permisje: 3,
        nowa_cena: 54.33,
        inna_cena_skupu: false,
    },
    // [11] xs - nowa_cena + cena_skup
    {
        nazwa: "XS",
        slug: "extreslim",
        typ: "rozmiar",
        kolory: null,
        rozmiary: null,
        objetosc: null,
        nadpisuje_cene: true,
        nowa_cena: 83.49,
        inna_cena_skupu: true,
        cena_skupu: 39.12
    },
];
